#!/bin/csh -f

# this script will check for all .gcard files inside a directory (given as argument)
# it will return those filenames, minus the .gcard


set dir = $1

# changing directory is cleaner than having to clean up
# the path from the names (ls a/* will give full path)
cd $dir

set gcards = `(\ls *.gcard  | awk -F".gcard" '{print $1}')`

echo $gcards

cd -

