#!/bin/csh -f


# cross sections as a function of theta or phi
# table is W,Q2

rm imageslist.txt ; ls imgcs/ > imageslist.txt

/opt/projects/htmlImageBrowserCreator/pageCreator -addRowTableVariable=wmass -addColumnTableVariable=q2 \
-addSelectableVariable=xaxis   -defaultPlot=imgcs/wmass-1.79_q2-3.00_xaxis-phi.png  -d=imgcs -imagesSize="1000 1000"

mv page.html cs.html

# cross sections as a function of W
# table is W,Q2

rm imageslist.txt ; ls imgcsw/ > imageslist.txt

/opt/projects/htmlImageBrowserCreator/pageCreator -addRowTableVariable=phi -addColumnTableVariable=q2 \
-defaultPlot=imgcs/wmass-1.79_q2-3.00_xaxis-phi.png  -d=imgcsw -imagesSize="1000 1000"

mv page.html csw.html


# structure functions
# table is Q2, structure function
# can choose W as running variable, or cos(theta)

rm imageslist.txt ; ls imgsf/ > imageslist.txt

/opt/projects/htmlImageBrowserCreator/pageCreator -addRowTableVariable=q2 -addColumnTableVariable=sf \
-addSelectableVariable=runningvar -defaultPlot=imgsf/q2-3.00_sf-LPT_runningvar-ctheta.png   -d=imgsf -imagesSize="1000 1200"

mv page.html sf.html
