#!/bin/csh -f

# manually copying come pics



rm imageslist.txt ; ls img/* > imageslist.txt

/opt/projects/htmlBrowserCreator/pageCreator -addRowTableVariable=conf   -addColumnTableVariable=zone \
-addSelectableVariable=plot -addSelectableVariable=region \
-defaultPlot=img/conf-t1.0_zone-target_plot-intocc_region-1.png -imagesSize="1000 1000"

mv page.html dc.html

