#!/bin/csh -f

# manually copying come pics



rm imageslist.txt ; ls img/* > imageslist.txt

/opt/projects/htmlImageBrowserCreator/pageCreator -addRowTableVariable=conf   -addColumnTableVariable=zone \
-addSelectableVariable=plot -addSelectableVariable=region \
-defaultPlot=img/conf-field090_zone-all_plot-zvertex_region-3.png -imagesSize="1000 1000"

mv page.html dc.html

