CREATED_F=elast_gen.F
LIBNAMES  = $(MAIN_DIRECTORY)$(DEBUG) 
LIBNAMES  +=clasutil fputil recutl bos fpack online_dummy c_bos_io
LIBNAMES  +=packlib mathlib kernlib lepto651 $(RECSIS_MD_LIBS)
SHARED_LIBS=$(RECSIS_SHARED_LIBS)
include $(CLAS_CMS)/Makefile
