#!/bin/csh -f


rm imageslist.txt ; ls img/* > imageslist.txt

/opt/projects/htmlImageBrowserCreator/pageCreator -addRowTableVariable=dist  -addColumnTableVariable=sector \
-defaultPlot=img/dist-dtfit_sector-all.png -imagesSize="1000 1000"

mv page.html cuts.html

rm imageslist.txt ; ls imgs/* > imageslist.txt

/opt/projects/htmlImageBrowserCreator/pageCreator -addRowTableVariable=slice -addColumnTableVariable=sector \
-defaultPlot=imgs/slice-4_sector-1.png -imagesSize="800 800" -d=imgs

mv page.html slices.html

