from init_env import init_environment

env = init_environment("clhep mu root")
env.Append(CXXFLAGS=['-std=c++14'])

# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

proton_pid_sources = Split("""src/proton_pid.cc
                              src/common_info.cc
                              src/histos.cc
                              src/proton_pid_selection.cc""")

proton_pid = env.Program(source = proton_pid_sources, target = 'proton_pid')

env.SharedLibrary(source = proton_pid_sources, target = 'ppid')


ana_proton_pid_sources = Split("""ana/tof_match.cc
                               """)

env.SharedLibrary(source = ana_proton_pid_sources, target = 'ana_ppid')