from init_env import init_environment

env = init_environment("clhep mu root")

# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

proton_pid_sources = Split("""src/proton_pid.cc
                              src/common_info.cc
                              src/histos.cc
                              src/proton_pid_selection.cc""")

proton_pid = env.Program(source = proton_pid_sources, target = 'proton_pid')
