from init_env import init_environment

env = init_environment("clhep mu root")
env.Append(CXXFLAGS=['-std=c++17']) # need c++17 for std::filesystem

# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

proton_pid_sources = Split("""src/proton_pid.cc
                              src/common_info.cc
                              src/histos.cc
                              src/proton_pid_selection.cc
                           """)

proton_pid = env.Program(source = proton_pid_sources, target = 'proton_pid')

env.SharedLibrary(source = proton_pid_sources, target = 'ppid')


ana_proton_pid_sources = Split("""ana/tof_match.cc
                                  ana/fit_and_calculate_pars.cc
                                  ana/show_dt_vs_mom.cc
                               """)

env.SharedLibrary(source = ana_proton_pid_sources, target = 'ana_ppid')