#!/bin/csh

if($1 == "-h" || $1 == ""  || $#argv != 2) then
	echo " "
	echo "Usage:   "
	echo "  >> go_concatenate ORIG_DIR DEST_DIR"
	echo "  "
	echo " ORIG_DIR: Input files directory"
	echo " DEST_DIR: Output files directory"
	echo " "
	echo "Example:"
	echo " go_concatenate /akasha/e1-6/all_files /akasha/e1-6/full_runs"
	exit 0
endif


set ORIG_DIR = $1
set DEST_DIR = $2
set ROOT_DIR = $DEST_DIR/root
set LOG_DIR  = $DEST_DIR/log
set COMMAND  = "/opt/work/projects/analysis/concatenate/concatenate"
mkdir -p $ROOT_DIR
mkdir -p $LOG_DIR

if(`filetest -e $COMMAND` == 0) then
	echo $COMMAND not found. Exiting
	exit 0
endif

echo " "
echo " Input files directory:   "  $ORIG_DIR
echo " Output files directory:  "  $DEST_DIR
echo " ROOT files directory:    "  $ROOT_DIR
echo " Command line:            "  $COMMAND
echo " "

set runs = (`\ls $ORIG_DIR | grep "\.mu" | awk -F. '{print $1}' | sort -u`)

foreach r ($runs)
	echo Concatenating $r...
	rm -rf $LOG_DIR/$r.log
	$COMMAND  $ORIG_DIR/$r*.mu -OUTPUT=$DEST_DIR/$r.mu -ROOT_OUTPUT=$ROOT_DIR/$r.root > $LOG_DIR/$r.log
	rm $ORIG_DIR/$r*.mu
end
