#!/bin/csh -f


rm imageslist.txt ; ls img/* > imageslist.txt


/opt/projects/htmlImageBrowserCreator/pageCreator -addRowTableVariable=wbin -addColumnTableVariable=q2bin \
-addSelectableVariable=plot -defaultPlot=img/wbin-1.29_q2bin-3.00_plot-corrPhiss.png -imagesSize="1000 1000" -d=img

mv page.html bin.html

