# Sources, executable and enviroment
# SUFFIXES:
# C++      .C  .cpp
# C        .c  .cc
# Fortran  .f


PROGRAMS     := get_tbla



# Where do you want it?
Obj_dir      := obj
Bin_dir      := .

# Turn on stuff you need with YES or NO
MY_FLAG   := NO
CLAS_FLAG := YES
CERN_FLAG := YES
ROOT_FLAG := YES
QT_FLAG   := NO
OPT       := YES
STATIC    := NO
DEBUG     := NO
SQL_MY    := YES
DB        := YES
FORTRAN   := YES
DUALMP    := NO


include $(MU)/makefiles/make.with
include $(MU)/makefiles/make.rules
include $(MU)/makefiles/make.env
