#!/bin/csh -f

# this function checks the farm for number of current jobs running
# it then returns how many more jobs can be launched until
# $1 = NMAXFARM is reached, given $2 = average # files per run 

set NMAXFARM = $1
set AVG_N    = $2

set NTODO    = 0

set NTOT = (`/site/bin/jobstat -u $CHEF | grep -v JOB | wc | awk '{print $1}'`)
if($NTOT < $NMAXFARM) then
	@ NTODO =  $NMAXFARM - $NTOT
	@ NTODO = $NTODO / $AVG_N
endif
echo $NTODO
