#!/bin/csh -f

set DIRS = ($DOUTPUT $DOUTPUT2 $DOUTPUT3)
set WHAT = (data ntuple/main root/main histos/monitoring histos/pdu log mu)

foreach D ($DIRS)

	set thisDir = $D/$DATASET/$PASS

	if($1 == "DEL") then
		echo deleting $thisDir ...
		rm -rf $thisDir
	endif

	foreach SD ($WHAT)
		echo creating $thisDir/$SD
		mkdir -p $thisDir/$SD
	end

end







