#!/bin/csh -f

# set up $LASTLAUNCHED to the first file, and re-create the directory structure

source cookEnvironment

# last launched
\echo resetting $LASTLAUNCHED
cd $CSCRIPTS/lists
rm -rf $LASTLAUNCHED ; head -1 $GOODRUNS > $LASTLAUNCHED
\echo

# output directories
cd $CSCRIPTS/functions
./createDirs DEL

# launched file
\echo resetting launched
cd $CSCRIPTS/lists
rm launched ; touch launched



