#!/bin/csh -f

# set up $LASTLAUNCHED to the first file, and create the directory structure

source cookEnvironment

\echo resetting $LASTLAUNCHED
cd $CSCRIPTS/lists
rm $LASTLAUNCHED ; head -1 $GOODRUNS > $LASTLAUNCHED
\echo

cd $CSCRIPTS/functions
./createDirs DEL




