import os
from util import scanFiles
env = Environment(ENV=os.environ)

pdf = env.PDF(target  = 'pfid.pdf',  source = 'pfid.tex')
#html = env.Command('efid.html', 'efid.tex', "go_htlatex $SOURCE");

#Depends(html, pdf)

#cleans = scanFiles('.', accept=["efid*", "*.aux"], reject=[".tex"])
##rint "to remove: ", cleans;

#Clean('efid.html', cleans)
