#!/bin/csh -f

echo aaa > ~/aaa
echo bbb

setenv JLAB_ROOT /site/12gev_phys
setenv JLAB_VERSION 1.2
source $JLAB_ROOT/$JLAB_VERSION/ce/jlab.csh

# Usage:
# go_simulate gcard TITLE workdir nevents

set gcard    = $1
set TITLE    = $2
set workdir  = $3
set NEVENTS  = $4
echo

set dir = $workdir/$TITLE
mkdir -p $dir

set origd = `pwd`

set NEXIST = `ls $dir/ | wc | awk '{print $1}'`
@ NMAX = $NEXIST + 10

# Look for first non existing dir
set SIMU    = 1
while ($SIMU < $NMAX)
	if(`filetest -e $dir/simu_$SIMU` == 0) then
		echo Starting Simulation $SIMU
		echo Using gemc `which gemc`
		echo
		mkdir -p $dir/simu_$SIMU
		chmod a+rwx $dir/simu_$SIMU

		ln -s $workdir/../experiments .
		ln -s $workdir/../sidis/eventfiles/sidis$SIMU".dat" sidis.dat

		echo gemc executable: `which gemc`
		echo
		ls -alp  
		echo    

		gemc -gcard=$gcard -N=$NEVENTS > $dir/simu_$SIMU/gemc.log

		# need to jput this into /mss/clas/clas12/clas12-testing/gemc
		# /site/bin/jput out.ev /mss/clas/clas12/clas12-testing/gemc/background_$SIMU".ev"
		
		cp out.ev $gcard $dir/simu_$SIMU

		exit    # exit here to stop at the first non-existin dir
	endif

 @ SIMU += 1

end
