#!/bin/csh -f

source /group/clas12/packages/setup.csh
module load clas12/pro

foreach d (`\ls | grep -v added | grep -v rootAdd`)
 $ROOTSYS/bin/hadd $d".root" $d/*.root
end

# creating dir so it's easier to scp
rm -rf added ; mkdir added
mv *.root added

# echoing dir to scp
cd added
set dirToCopy = `pwd`

# from the local computer
echo
echo "From the local computer:"
echo 
echo "scp -r ftp:$dirToCopy ."
echo "mv added/*.root ."
echo "rm -rf added"
