#!/bin/csh -f


rm imageslist.txt ; ls img/ > imageslist.txt


/opt/projects/htmlImageBrowserCreator/pageCreator -addRowTableVariable=wbin -addColumnTableVariable=q2bin \
-addSelectableVariable=plot -addSelectableVariable=vcut -defaultPlot=img/wbin-1.67_q2bin-3.00_plot-thetas_vcut-0.04.png -imagesSize="1000 1000"

mv page.html radCor.html

