#!/bin/csh -f

setenv CLAS_CALDB_RUNINDEX calib_user.RunIndexe1_6

setenv PASS         pass3
setenv VERSION      v1
setenv DATASET      e1-6a
setenv CHEF         `whoami`                              # user name of chef

setenv CSCRIPTS     /home/clase1-6/recook                 # cooking scripts locations and executables
setenv DOUTPUT      /work/clas/production/clase1-6        # disk output
setenv DOUTPUT2     /work/clas/production2/clase1-6       # disk output
setenv DOUTPUT3     /work/clas/production3/clase1-6       # disk output

setenv LASTLAUNCHED $CSCRIPTS/lists/lastLaunched          # file containing the last run launched
setenv GOODRUNS     $CSCRIPTS/lists/goodRuns              # list of good runs
setenv EMPTYRUNS    $CSCRIPTS/lists/emptyTargetRuns       # list of empty target runs
setenv FMOND        $CSCRIPTS/fmon                        # files monitor

setenv DATA_OUT     $DOUTPUT/$DATASET/$PASS               # datafiles
setenv NTUP_OUT     $DOUTPUT2/$DATASET/$PASS              # ntuple
setenv ROOT_OUT     $DOUTPUT2/$DATASET/$PASS              # root
setenv HIST_OUT     $DOUTPUT3/$DATASET/$PASS              # monitoring histos, pdu

setenv MU_OUT       $DOUTPUT3/$DATASET/$PASS              # mu output

setenv SILO_OUT     /mss/clas/$DATASET/production/$PASS/$VERSION     # silo path of output
setenv SILO_IN      /mss/clas/$DATASET/data                          # silo path of input

setenv HIST_SIZE1    9080     # sometimes histos slightly differ on the file size
setenv HIST_SIZE2    9080
setenv DATA_MIN_SIZE 1100000
setenv NTP_MIN_SIZE  200000


# environment for executables
setenv PATH /apps/gcc/4.8.0/bin:$PATH
setenv LD_LIBRARY_PATH /apps/gcc/4.8.0/lib64:$LD_LIBRARY_PATH
setenv CXX /apps/gcc/4.8.0/bin/c++
setenv CC  /apps/gcc/4.8.0/bin/gcc

# CLAS6 software
setenv CLASPREFIX /u/home/clase1-6/clas6-source
setenv CLAS6INC ${CLASPREFIX}/build/include
setenv CLAS6LIB ${CLASPREFIX}/build/lib
setenv CLAS6BIN ${CLASPREFIX}/build/bin
setenv ALIGNBITS 64
setenv PYTHONPATH ${CLASPREFIX}/lib/python:${PYTHONPATH}

# clas paths
setenv CLAS_PARMS /group/clas/parms
setenv LD_LIBRARY_PATH ${CLAS6LIB}:${LD_LIBRARY_PATH}

setenv PATH ${CLASPREFIX}/scripts:${CLAS6BIN}:${PATH}
set path = (/group/clas/tools/caldb $CLAS6BIN /apps/bin $path)

# perl scripts for clasdb
setenv PERL5LIB /group/clas/tools/caldb

# cernlib
setenv CERNLIB /usr/lib64/cernlib/2006/lib

# mysql
setenv MYSQLINC /usr/include/mysql
setenv MYSQLLIB /usr/lib64/mysql

# tcl
setenv TCLLIB /usr/lib
