#!/bin/csh -f


setenv PASS         pass3
setenv VERSION      v1
setenv DATASET      e1-6a
setenv CHEF         `whoami`                              # user name of chef

setenv CSCRIPTS     /home/clase1-6/recook                 # cooking scripts locations
setenv DOUTPUT      /work/clas/production/clase1-6        # disk output

setenv LASTLAUNCHED $CSCRIPTS/lists/lastLaunched          # file containing the last run launched
setenv GOODRUNS     $CSCRIPTS/lists/goodRuns              # list of good runs
setenv EMPTYRUNS    $CSCRIPTS/lists/emptyTargetRuns       # list of empty target runs

setenv DATA_OUT     $DOUTPUT/$DATASET/$PASS               # datafiles
setenv NTUP_OUT     $DOUTPUT/$DATASET/$PASS               # ntuple
setenv ROOT_OUT     $DOUTPUT/$DATASET/$PASS               # root
setenv HIST_OUT     $DOUTPUT/$DATASET/$PASS               # monitoring histos, pdu

setenv SILO_OUT     /mss/clas/$DATASET/production/$PASS/$VERSION     # silo path of output
setenv SILO_IN      /mss/clas/$DATASET/data                          # silo path of input

setenv HIST_SIZE     9080
setenv DATA_MIN_SIZE 1100000
setenv NTP_MIN_SIZE  200000


# environment for executables
setenv CLASPREFIX /work/clas/clas12/ungaro/clas6-trunk
setenv GCC /apps/gcc/4.8.0
setenv CERNLIB /usr/lib64/cernlib/2006/lib

setenv PYTHONPATH ${CLASPREFIX}/lib/python

setenv MYSQLINC /usr/include/mysql
setenv MYSQLLIB /usr/lib64/mysql

setenv CLAS6INC ${CLASPREFIX}/build/include
setenv CLAS6LIB ${CLASPREFIX}/build/lib
setenv CLAS6BIN ${CLASPREFIX}/build/bin

setenv TCLLIB /usr/lib

# this line is commented out until gcc 4.8 software is installed on ifarm
# this line needs to be done at command line after jlab.csh is sourced
setenv PATH ${GCC}/bin:${PATH}
setenv PATH ${CLASPREFIX}/scripts::${CLAS6BIN}:${PATH}

if( ! $?LD_LIBRARY_PATH) then
	setenv LD_LIBRARY_PATH ""
endif

setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${GCC}/lib64:${CLAS6LIB}

setenv CLAS_PARMS /group/clas/parms

# clas path
set path = (/group/clas/tools/caldb $CLAS6BIN $path)
set path = (/apps/bin $path)
set path = (/apps/cmake/bin $path)
