from init_env import init_environment

env = init_environment("clhep mu root")
env.Append(CXXFLAGS=['-std=c++17']) # need c++17 for std::filesystem


# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

mom_corr_sources = Split("""src/momentum.cc
                            src/common_info.cc
                            src/histos.cc
                            src/mom_corr.cc""")

vertex = env.Program(source = mom_corr_sources, target = 'e_mom_corr')
