from init_env import init_environment

env = init_environment("clhep mu root")
env.Append(CXXFLAGS=['-std=c++17']) # need c++17 for std::filesystem


# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

mom_corr_sources = Split("""src/momentum.cc
                            src/common_info.cc
                            src/histos.cc
                            src/mom_corr.cc""")

e_corr = env.Program(source = mom_corr_sources, target = 'e_mom_corr')

e_corr_lib = env.SharedLibrary(source = mom_corr_sources, target = 'e_mom_corr')

ana_e_corr_sources=Split("""src/common_info.cc
                            ana/show_1d.cc
                            ana/show_2d.cc""")

ana_e_corr_lib = env.SharedLibrary(source = ana_e_corr_sources, target = 'ana_e_mom_corr')
