#!/bin/csh -f

\echo
\echo OTHER_FILES: $CSCRIPTS/recsis_$DATASET".tcl"
\echo OTHER_FILES: $CSCRIPTS/executables/user_ana
\echo OTHER_FILES: $CSCRIPTS/executables/bos2mu
\echo OTHER_FILES: $CSCRIPTS/executables/nt10maker
\echo OTHER_FILES: $CSCRIPTS/executables/pdu
\echo OTHER_FILES: $CSCRIPTS/functions/verifyConditions
\echo OTHER_FILES: $CSCRIPTS/go_COOK
\echo
