#!/bin/csh 

set dir   = /work/clas/disk5/ungaro/acceptance/gsim_elastic
set fromd = /u/home/ungaro/projects/analysis/acceptance/gsim/farm


set NMAX = (750)

set N = 0
if($1 == "batch") then
	set N = (`/site/bin/jobstat -u ungaro | grep e16 | grep prod | wc | awk '{print $1}'`)
endif

@ REM = $NMAX - $N

echo $N process already running, $REM to launch to reach $NMAX ...

set i = (1)
while ($i <= $REM)
	rm -f gsim.jsub
	echo  JOBNAME: e16 montecarlo                   > gsim.jsub
	echo  PROJECT: e1-6a                           >> gsim.jsub
	echo  MAIL:    ungaro@jlab.org                 >> gsim.jsub
	echo  TRACK:   simulation                      >> gsim.jsub
	echo  COMMAND: go_MC $dir elast_gen            >> gsim.jsub
	echo  OS:      linux                           >> gsim.jsub
	echo  OTHER_FILES: $fromd/go_MC                >> gsim.jsub
	echo  OTHER_FILES: $fromd/input.aao            >> gsim.jsub
	echo  OTHER_FILES: $fromd/elas_5.7.inp         >> gsim.jsub
	echo  OTHER_FILES: $fromd/gsim_simue16.ffread  >> gsim.jsub
	echo  OTHER_FILES: $fromd/recsis_simue16.tcl   >> gsim.jsub
	echo  OTHER_FILES: $fromd/bins/aao_rad         >> gsim.jsub
	echo  OTHER_FILES: $fromd/bins/elast_gen       >> gsim.jsub
	echo  OTHER_FILES: $fromd/bins/gsim_bat        >> gsim.jsub
	echo  OTHER_FILES: $fromd/bins/gpp             >> gsim.jsub
	echo  OTHER_FILES: $fromd/bins/user_ana        >> gsim.jsub
	echo  OTHER_FILES: $fromd/bins/bos2mu          >> gsim.jsub
	echo
	
	/site/bin/jsub gsim.jsub

	echo Launching simulation $i 
	@ i += 1
end

