#!/bin/csh -f
# enviroment variables for e16
# to use with source

source /site/12gev_phys/production.csh 1.3
source /home/clase1-6/recook/cookEnvironment

setenv CLAS_PARMS /home/ungaro/CLAS_PARMS
setenv CLAS_PACK /home/clasg11/top_dir
setenv CLAS_LIB /home/clasg11/top_dir/bin/LinuxRHEL6
setenv CLAS_CMS $CLAS_PACK/cms
setenv OS_NAME LinuxRHEL6
setenv OS_CLAS LinuxRHEL6
setenv OSNAME LinuxRHEL6
