#!/bin/zsh

# copy all sectors theta match to cuts and pars
cp img/cut-01-cc-theta-match_sector-all.png img/cut-01-cc-theta-match-compare_sector-all.png
cp img/cut-01-cc-theta-match_sector-all.png img/cut-01-cc-theta-match-pars_sector-all.png




# copied from README
rm -rf imageslist.txt ; ls img > imageslist.txt
../../../htmlBrowserCreator/pageCreator -addRowTableVariable=cut  \
                                        -addColumnTableVariable=sector \
-defaultPlot=img/cut-01-cc-theta-match-compare_sector-1.png -imagesSize="1200 1200"
mv page.html cuts.html





# copied from README
rm -rf imageslist.txt ; ls img_slices > imageslist.txt
../../../htmlBrowserCreator/pageCreator -addRowTableVariable=slice \
                                        -addColumnTableVariable=cut \
                                        -addSelectableVariable=sector \
-defaultPlot=img_slices/slice-01_cut-01-cc-theta-slice_sector-1.png \
-imagesSize="1200 1200" -d=img_slices
mv page.html slices.html