from init_env import init_environment

env = init_environment("clhep mu root")
env.Append(CXXFLAGS=['-std=c++14'])


# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

e_pid_sources = Split("""src/e_pid.cc
                         src/common_info.cc
                         src/histos.cc
                         src/e_pid_selection.cc""")

e_pid = env.Program(source = e_pid_sources, target = 'e_pid')

env.SharedLibrary(source = e_pid_sources, target = 'epid')

ana_e_pid_sources = Split("""ana/cc_theta_match.cc
                             ana/show_cc_theta_match.cc
                             ana/show_cc_phi_match.cc
                             ana/cc_time_match.cc
                             ana/show_cc_time_match.cc
                             """)

env.SharedLibrary(source = ana_e_pid_sources, target = 'ana_epid')
