from init_env import init_environment

env = init_environment("clhep mu root")
env.Append(CXXFLAGS=['-std=c++14'])


# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

e_pid_sources = Split("""src/e_pid.cc
                         src/common_info.cc
                         src/histos.cc
                         src/e_pid_selection.cc""")

e_pid = env.Program(source = e_pid_sources, target = 'e_pid')

# env.SharedLibrary(source = e_pid_sources, target = 'epid')

e_pid_msources = Split("""e_pid.C
                          src/common_info.cc
                          ana/cc_match.cc""")

e_pid_macro = env.Program(source = e_pid_msources, target = 'e_pid_analysis')
