#!/bin/csh -f

source /home/ungaro/analysis/farm/clas6/muCooking/cookEnvironment

# chef setup
# ----------

set NMAX   = 10
set COOK   = $CSCRIPTS/go_COOK
set DISKIN = /work/clas/production/clase1-6/e1-6a/pass3/data
set SOURCE = SILO # Can be DISK to get mu files in the above dir

# end of chef setup

if($1 == "restart" ) then
	rm  $LASTF ;
	head -1 $LISTF > $LASTF
endif

set DEBUG = no
if($1 == "DEBUG") then
	set DEBUG = yes
endif


# Start Processing --------------------

set LAST    = (`cat $LASTF`)

@ NMAX -= 1
foreach r (`grep -A$NMAX $LAST $LISTF`)
	echo Launching $r

	./createJsub $r $SOURCE

	if($DEBUG == "yes") then
		cat jsub.$DATASET
	else
		/site/bin/jsub jsub.$DATASET
	endif

	set NEW_LAST = (`grep -A1 $r  lists/list_$DATASET".txt" | tail -1`)
	rm  $LASTF ; echo $NEW_LAST > $LASTF
	echo New last run is $NEW_LAST
end

