#!/bin/csh -f

setenv DATASET   e1-6a
setenv PASS      pass1
setenv VERS      v1
setenv RUNI      calib_user.RunIndexe1_6

setenv PROJECT  e1-6a
setenv MAIL     ungaro@jlab.org

setenv CSCRIPTS /home/ungaro/analysis/farm/clas6/muCooking
setenv BOS2MU   /home/ungaro/projects/muEvent/bin/bos2mu
setenv OUTPUTD  /work/clas/clas12/ungaro/$DATA

setenv SILOIN   /mss/clas/$DATA/production/$PASS/$VERS/data

set LISTF =  $CSCRIPTS/lists/list_$DATA".txt"       # List ofruns
set LASTF =  $CSCRIPTSlists/last_launched_$DATA     # Contains the last job launched
