#!/bin/csh -f

# User Information --------------------------

set BOS2MU  = /home/ungaro/projects/CLAS_Event/bos2mu
set COOK    = /home/ungaro/projects/mu_cooking_scripts/go_COOK
set DIR     = /work/clas/disk1/ungaro/$DATA

# End of User Information --------------------


./go_files $DATASET $PASS $VERS $RUNI $PROJECT $MAIL $BOS2MU $COOK $DIR
/site/bin/jsub jsub.$DATA
#cat jsub.$DATA


