#!/bin/csh -f

set RUN    = $1   # run number
set SOURCE = $2   # SILO or DISK

set LOC = $SILOIN
if($SOURCE == "DISK") then
	set LOC = $DISKIN
endif

# Creating list of files
set list  = (`\ls $LOC/run_$RUN"_"*`)
rm -rf list_files ; touch list_files

foreach x ($list)
	echo "INPUT_FILES:" >> list_files
	echo $x             >> list_files
end

# Creating jsub file
rm -f jsub.$DATASET
\echo JOBNAME:" "$DATASET reduction    > jsub.$DATASET
\echo PROJECT:" "$PROJECT             >> jsub.$DATASET
\echo MAIL:"    "$MAIL                >> jsub.$DATASET
\echo OS:"      "centos65             >> jsub.$DATASET
\echo TRACK:"   "reconstruction       >> jsub.$DATASET
\echo " "                             >> jsub.$DATASET
\echo OTHER_FILES: $BOS2MU            >> jsub.$DATASET
\echo OTHER_FILES: $CSCRIPTS/go_COOK  >> jsub.$DATASET
\echo MEMORY:      500 MB             >> jsub.$DATASET
\echo " "                             >> jsub.$DATASET
\echo "COMMAND: ./go_COOK "           >> jsub.$DATASET
\echo " "                             >> jsub.$DATASET
cat list_files                        >> jsub.$DATASET

# Cleaning up
rm list_files

