#!/bin/csh -f

set RUN    = $1   # run number
set SOURCE = $2   # SILO or DISK

set LOC = $SILOIN
if($SOURCE == "DISK") then
	set LOC = $DISKIN
endif

# Creating list of files
set list  = (`\ls $LOC/run_$RUN"_"*`)
rm -rf list_files ; touch list_files

foreach x ($list)
	echo "INPUT_FILES:" >> list_files
	echo $x             >> list_files
end

# Creating jsub file
rm -f jsub.$DATA
echo JOBNAME:" "$DATA reduction       > jsub.$DATA
echo PROJECT:" "$PROJECT             >> jsub.$DATA
echo MAIL:"    "$MAIL                >> jsub.$DATA
echo OS:"      "centos65             >> jsub.$DATA
echo TRACK:"   "reconstruction       >> jsub.$DATA
echo " "                             >> jsub.$DATA
echo OTHER_FILES: $BOS2MU            >> jsub.$DATA
echo OTHER_FILES: $COOK              >> jsub.$DATA
echo MEMORY:      500 MB             >> jsub.$DATA
echo " "                             >> jsub.$DATA
echo "COMMAND: ./go_COOK "           >> jsub.$DATA
echo " "                             >> jsub.$DATA
cat list_files                       >> jsub.$DATA

# Cleaning up
rm list_files

