#!/bin/csh -f

set DATA    = e1-6a
set DIR     = /work/clas/disk3/ungaro/$DATA
set MDIR    = /akasha/e1-6_p1/mu_files



set NFILES  = (`\ls $DIR | wc | awk '{print $1}'`)
echo
echo $NFILES files in $DIR
echo

@ NFILES -= 10
echo Copying $NFILES files to $MDIR

set fl = (`\ls $DIR | head -$NFILES | grep \.mu`)

foreach f($fl)
	echo $f
	scp $DIR/$f mauri:$MDIR
	rm $DIR/$f
end





