#!/bin/csh -f

source /site/12gev_phys/production.csh 1.2
source /home/ungaro/analysis/farm/clas6/muCooking/cookEnvironment

set file   = (`ls run*`)
set run    = (`ls run* | awk -F_ '{print $2}'`)
set ext    = (`ls run* | awk -F_ '{print $3}' | awk -F. '{print $2}'`)
set output = $run"."$ext".mu"
set INFOS  = (\""$DATASET" "$PASS" Production Data\")

echo
echo File: $file
echo

./bos2mu -DC_PLANES=1 -INFOS="$INFOS" -RUN_INDEX=$RUNI -OUTPUT=$output $file
echo Copying Files into $DIR
echo
mkdir -p $OUTPUTD/mu
cp  *.mu $OUTPUTD/mu

ls -alp

