#!/bin/csh -f

set RUN  = $1
set DATA = $2
set PASS = $3
set VERS = $4
set RUNI = $5

set PROJECT = $6
set MAIL    = $7
set BOS2MU  = $8
set COOK    = $9
set DIR     = $10

# Creating list of files
set list  = (`\ls /mss/clas/$DATA/production/$PASS/$VERS/data/run_$RUN"_"*`)
rm -rf list_files ; touch list_files

foreach x ($list)
 echo "INPUT_FILES:" >> list_files
 echo $x             >> list_files
end

# Creating jsub file
rm -f jsub.$DATA
echo JOBNAME:" "$DATA reduction                   > jsub.$DATA
echo PROJECT:" "$PROJECT                         >> jsub.$DATA
echo MAIL:"    "$MAIL                            >> jsub.$DATA
echo OS:"      "linux64                          >> jsub.$DATA
echo TRACK:"   "reconstruction                   >> jsub.$DATA
echo " "                                         >> jsub.$DATA
echo OTHER_FILES: $BOS2MU                        >> jsub.$DATA
echo OTHER_FILES: $COOK                          >> jsub.$DATA
echo MEMORY:      500 MB                         >> jsub.$DATA
echo " "                                         >> jsub.$DATA
echo "COMMAND: ./go_COOK "$DATA $RUNI $PASS $DIR >> jsub.$DATA
echo " "                                         >> jsub.$DATA
cat list_files                                   >> jsub.$DATA

# Cleaning up
rm list_files

