#!/bin/csh -f

# this script is run from a JLab cue machine to delete
# files that are done concatenating in mauri's machine

set DATASET  = e1-6a
set PASS     = pass1
set IDIR      = /work/clas/clas12/ungaro/$DATASET/$PASS/mu


set runs = `cat /home/ungaro/projects/analysis/farm/clas6/muCooking/canBeDeletedAtJlab`

foreach r ($runs)
	echo removing $IDIR/$r*
	rm $IDIR/$r*
end
