#!/bin/csh -f

# this script is run from a JLab cue machine to delete
# files that are done concatenating in mauri's machine

set DATASET  = e1-6a
set PASS     = pass1
set IDIR      = /work/clas/clas12/ungaro/$DATASET/$PASS


set runs = `cat /home/ungaro/analysis/farm/clas6/muCooking/canBeDeletedAtJlab`

echo $runs


