#!/bin/tcsh

set Wmin            = 1490
set Wmax            = 2200
set dW              = 10

# This will load the etamaid2001 values

if($1 == "etamaid2001")  then
	set model    = 'maid1?switch=64'
	set default1 = '&param1=1&param2=1&param3=1&param4=1&param7=1&param8=1&param11=1&param12=1&param13=1&param14=1&param15=1&param17=1&param18=1&param19=1&param20=1&param21=1&param22=1&param50=2'
endif

mkdir -p $1

set url      = 'http://wwwkph.kph.uni-mainz.de/cgi-bin/'
set l = 0

while( $l < 6 )
	set iQ2 = 0
	while( $iQ2 < 5 )
		set dQ2 = 0
		while( $dQ2 < 10)
			set cQ2 = 0
			while ( $cQ2 < 10)
				
				set Q2 = $iQ2"."$dQ2$cQ2
				set URL = "$url""$model""&value1="$l"$default1""&value35="$Q2"&value36="$Wmin"&value41="$dW"&value42="$Wmax
				wget "$URL" -O $1/Q2_$Q2"_l_"$l".tbl"

				# echo $Q2 $l
				@ cQ2 += 5
			end
			@ dQ2 += 1
		end
		@ iQ2 += 1
	end

	# last Q2 point is 5
	set Q2 = 5
	set URL = "$url""$model""&value1="$l"$default1""&value35="$Q2"&value36="$Wmin"&value41="$dW"&value42="$Wmax
	wget "$URL" -O $1/Q2_$Q2"_l_"$l".tbl"
	
	@ l += 1
end
