from init_env import init_environment

env = init_environment("clhep mu root")


# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

vertex_sources = Split("""src/vertex.cc
                          src/common_info.cc
                          src/histos.cc
                          src/vertex_corrsel.cc""")

vertex = env.Program(source = vertex_sources, target = 'vertex_corr_sel')
