from init_env import init_environment

env = init_environment("clhep mu root")


# Include Path
incpath = ['src']
env.Append(CPPPATH = incpath)

p_fid_sources = Split("""src/p_fiducial.cc
                          src/common_info.cc
                          src/histos.cc
                          src/fiducial_cut.cc""")

p_fid = env.Program(source = p_fid_sources, target = 'p_fiducial')
